runtime: php55
api_version: 1

handlers:
- url: /static
  static_dir: static_files

- url: /list.*
  script: list.php

- url: /edit.*
  script: edit.php

- url: /load.*
  script: load.php

- url: /.*
  script: p_404.php